In [6]:
import numpy as np
import pandas as pd
import os
os.chdir('/Users/younghun/Desktop/gitrepo/data/woochuri')

In [8]:
woo_1 = pd.read_excel('woochuri_2008_2011.xlsx')
woo_1.shape

(2815, 6)

In [10]:
woo_1.isnull().sum()

year          2587
month         2570
day           1934
name             0
weight(kg)       0
unit_price       1
dtype: int64

In [21]:
woo_1 = woo_1[woo_1['unit_price'].notna()]
woo_1.isnull().sum()

year          2586
month         2569
day           1933
name             0
weight(kg)       0
unit_price       0
dtype: int64

In [22]:
# 결측치 ffill로 대체
woo_1 = woo_1.fillna(method='ffill')
woo_1.isnull().sum()

year          0
month         0
day           0
name          0
weight(kg)    0
unit_price    0
dtype: int64

In [23]:
woo_1.tail(30)

        year  month day name  weight(kg)  unit_price
2785  2011.0   12.0  19   등뼈       38.90      2500.0
2786  2011.0   12.0  19  등갈비       10.80     12000.0
2787  2011.0   12.0  19   목살       12.40     15500.0
2788  2011.0   12.0  20  미후지       16.90      4500.0
2789  2011.0   12.0  20   등뼈       39.90      2500.0
2790  2011.0   12.0  20   갈비       17.00      7800.0
2791  2011.0   12.0  20   안심       15.00      7500.0
2792  2011.0   12.0  20  미니족       10.00      6500.0
2793  2011.0   12.0  21  미전지       17.40      9000.0
2794  2011.0   12.0  21  미삼겹       12.30     15500.0
2795  2011.0   12.0  22   등뼈       38.40      2500.0
2796  2011.0   12.0  23   등뼈       38.50      2500.0
2797  2011.0   12.0  23  미삼겹        6.40     14500.0
2798  2011.0   12.0  23  미전지       18.00      9000.0
2799  2011.0   12.0  26  미후지       14.40      4500.0
2800  2011.0   12.0  26   등뼈       16.50      2500.0
2801  2011.0   12.0  27   등뼈       21.10      2500.0
2802  2011.0   12.0  27   사태       18.10      9000.0
2803  2011.0   12.0  28   등뼈       39.30      2500.0
2804  2011.0   12.0  28  미전지       33.40      8500.0
2805  2011.0   12.0  29  등갈비       19.20     12000.0
2806  2011.0   12.0  29   등뼈       73.60      2500.0
2807  2011.0   12.0  29  미삼겹        6.50     13800.0
2808  2011.0   12.0  29   목살       11.20     13500.0
2809  2011.0   12.0  29   갈비       15.20      7800.0
2810  2011.0   12.0  29   장족        3.30      5800.0
2811  2011.0   12.0  30   등뼈       41.50      2500.0
2812  2011.0   12.0  30  미후지       16.70      4500.0
2813  2011.0   12.0  31   삼겹        7.00     13500.0
2814  2011.0   12.0  31   등뼈       20.96      2500.0